name: Deploy Loan Approval App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Authenticate with GCP using the service account key
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud CLI
        run: gcloud auth configure-docker

      # Build & Push Docker Image to Google Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/daxa-ai/loan-approval-app:${{ github.sha }} .
          docker push gcr.io/daxa-ai/loan-approval-app:${{ github.sha }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy loan-approval-app \
            --image gcr.io/daxa-ai/loan-approval-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
